### ISSUE TITLE
Region is not reflected in case of no us-south (eu-de...)

### ISSUE THREAD

**Issue by khayama-zz** [l2fprod/vpc-diagram-exporter#10]
Region is not reflected in case of no us-south (eu-de...)

**Comment by khayama-zz** [comment]
![khayama-vpc-1 gv_copy](https://user-images.githubusercontent.com/13445142/84177098-5e8c1100-aabd-11ea-9985-5ae50a001d0c.png)

**Comment by l2fprod** [comment]
https://github.com/l2fprod/vpc-diagram-exporter/commit/f5075d7c55f58e56f2cc78a5c952e39e55bf78f9 should fix this

let me know if you still see a problem

**Comment by khayama-zz** [comment]
Also fixed for me, thanks!
