### ISSUE TITLE
fip of 'NoneType' breaking dump.py

### ISSUE THREAD

**Issue by dbennerIBM** [l2fprod/vpc-diagram-exporter#6]
Traceback (most recent call last):
  File "dump.py", line 101, in <module>
    for fipIndex, fip in enumerate(nic['floating_ips']):
TypeError: 'NoneType' object is not iterable

I'm on Gen 1 of the VPC.  Thanks for any help

**Comment by l2fprod** [comment]
please try again with the latest if you get a chance
