### ISSUE TITLE
Exporting meet KeyError in /app/dump.py

### ISSUE THREAD

**Issue by owhc** [l2fprod/vpc-diagram-exporter#9]
API endpoint:      https://cloud.ibm.com   
Region:            us-south   
User:              owenchen@tw.ibm.com   
Account:           Owen Chen's Account (fa23dcfce42e79b57526566fcac2cd55) <-> 1503677   
Resource group:    cloudnative-dev   
CF API endpoint:      
Org:                  
Space:                
/home/Downloads # vpc-diagram-exporter
ibmcloud is floating-ips
ibmcloud is images
ibmcloud is ike-policies
ibmcloud is instances
ibmcloud is instance-profiles
ibmcloud is ipsec-policies
ibmcloud is keys
ibmcloud is load-balancers
ibmcloud is network-acls
ibmcloud is public-gateways
ibmcloud is regions
ibmcloud is security-groups
ibmcloud is subnets
ibmcloud is vpcs
ibmcloud is vpn-gateways
ibmcloud is volumes
ibmcloud is zones eu-gb
ibmcloud is zones us-east
ibmcloud is zones us-south
Traceback (most recent call last):
  File "/app/dump.py", line 64, in <module>
    vpcIdToVPC[subnet['vpc']['id']]['subnets'].append(subnet)
KeyError: 'r006-116ef604-baee-453a-bb4b-3c484d14aa3b'

**Comment by l2fprod** [comment]
@owhc is that with Gen 1 or Gen 2?

**Comment by l2fprod** [comment]
just pushed a fix.

issue came from the fact the VPC and its subnets were in different resource groups

running `ibmcloud target --unset-resource-group` before the tool will make sure all VPCs are returned
